import { LoanInterface, StatusTypes } from "./types";

export const loansTestData: Array<any> = [
  {
    id: "1231",
    token: "DAI",
    collateralToken: "ETH",
    transactionHash: "0xxxxxxxxxxxxxxxxxxxxxxx",
    terms: {
      interestRate: 17,
      collateralRatio: 0,
      maxLoanAmount: 100,
      duration: 1,
      expiryAt: 1600200720000,
    },
    startDate: 1600114320000,
    endDate: 1600200720000,
    amountBorrowed: 100,
    status: StatusTypes["Active"],
    totalRepaidAmount: 0,
    totalOwedAmount: 100.05,
    totalCollateralDepositsAmount: 0,
    totalCollateralWithdrawalsAmount: 0,
    loanType: "Unsecured",
    compound: {
      supplied: 10,
      earned: 0,
    },
  },
  {
    id: "1242",
    token: "DAI",
    collateralToken: "LINK",
    transactionHash: "0xxxxxxxxxxxxxxxxxxxxxxx",
    terms: {
      interestRate: 11,
      collateralRatio: 70,
      maxLoanAmount: 893,
      duration: 6,
      expiryAt: 1600294320000,
    },
    startDate: 1599775920000,
    endDate: 1600294320000,
    amountBorrowed: 893,
    status: StatusTypes["Active"],
    repayments: [{ amount: 1 }],
    totalRepaidAmount: 0,
    totalOwedAmount: 893,
    collateralDeposits: [{ amount: 39 }],
    totalCollateralDepositsAmount: 49,
    collateralWithdrawns: [{ amount: 1 }],
    totalCollateralWithdrawalsAmount: 0,
    loanType: "Secured",
    compound: {
      supplied: 399,
      earned: 0,
    },
  },
  {
    id: "1253",
    token: "USDC",
    collateralToken: "LINK",
    transactionHash: "0xxxxxxxxxxxxxxxxxxxxxxx",
    terms: {
      interestRate: 1,
      collateralRatio: 60,
      maxLoanAmount: 34,
      duration: 31,
      expiryAt: 1602540720000,
    },
    startDate: 1599948720000,
    endDate: 1602540720000,
    amountBorrowed: 34,
    status: StatusTypes["Active"],
    repayments: [{ amount: 1 }],
    totalRepaidAmount: 0,
    totalOwedAmount: 50,
    collateralDeposits: [{ amount: 4 }],
    totalCollateralDepositsAmount: 4,
    collateralWithdrawns: [],
    totalCollateralWithdrawalsAmount: 0,
    loanType: "Secured",
    compound: {
      supplied: 0,
      earned: 0,
    },
  },
  {
    id: "1264",
    token: "DAI",
    collateralToken: "LINK",
    transactionHash: "0xxxxxxxxxxxxxxxxxxxxxxx",
    terms: {
      interestRate: 1,
      collateralRatio: 160,
      maxLoanAmount: 10,
      duration: 1,
      expiryAt: 1599948720000,
    },
    startDate: 1599862320000,
    endDate: 1599948720000,
    amountBorrowed: 10,
    status: StatusTypes["Active"],
    repayments: [{ amount: 1 }],
    totalRepaidAmount: 0,
    totalOwedAmount: 10,
    collateralDeposits: [{ amount: 0.81 }],
    totalCollateralDepositsAmount: 2.04,
    collateralWithdrawns: [{ amount: 1 }],
    totalCollateralWithdrawalsAmount: 0,
    loanType: "Secured",
    compound: {
      supplied: 0,
      earned: 0,
    },
  },
  {
    id: "1239",
    token: "DAI",
    collateralToken: "ETH",
    transactionHash: "0xxxxxxxxxxxxxxxxxxxxxxx",
    terms: {
      interestRate: 1,
      collateralRatio: 60,
      maxLoanAmount: 10,
      duration: 1,
      expiryAt: 1599948720000,
    },
    startDate: 1599862320000,
    endDate: 1599948720000,
    amountBorrowed: 10,
    status: StatusTypes["Closed"],
    repayments: [{ amount: 1 }],
    totalRepaidAmount: 0,
    totalOwedAmount: 10,
    collateralDeposits: [{ amount: 0.81 }],
    totalCollateralDepositsAmount: 0.81,
    collateralWithdrawns: [{ amount: 1 }],
    totalCollateralWithdrawalsAmount: 0,
    loanType: "Secured",
    compound: {
      supplied: 0,
      earned: 0,
    },
  },
  {
    id: "4643",
    token: "DAI",
    collateralToken: "ETH",
    transactionHash: "0xxxxxxxxxxxxxxxxxxxxxxx",
    terms: {
      interestRate: 1,
      collateralRatio: 60,
      maxLoanAmount: 200,
      duration: 1,
      expiryAt: 1599948720000,
    },
    startDate: 1599862320000,
    endDate: 1599948720000,
    amountBorrowed: 200,
    status: StatusTypes["Closed"],
    repayments: [{ amount: 1 }],
    totalRepaidAmount: 0,
    totalOwedAmount: 200,
    totalCollateralDepositsAmount: 0,
    totalCollateralWithdrawalsAmount: 0,
    loanType: "Unsecured",
    compound: {
      supplied: 0,
      earned: 0,
    },
  },
  {
    id: "935",
    token: "USDC",
    collateralToken: "ETH",
    transactionHash: "0xxxxxxxxxxxxxxxxxxxxxxx",
    terms: {
      interestRate: 1,
      collateralRatio: 60,
      maxLoanAmount: 60,
      duration: 1,
      expiryAt: 1599948720000,
    },
    startDate: 1599862320000,
    endDate: 1599948720000,
    amountBorrowed: 60,
    status: StatusTypes["Closed"],
    totalRepaidAmount: 0,
    totalOwedAmount: 0,
    totalCollateralDepositsAmount: 0,
    totalCollateralWithdrawalsAmount: 0,
    loanType: "Unsecured",
    compound: {
      supplied: 0,
      earned: 0,
    },
  },
];
