import { LoanInterface, StatusTypes } from "./types";

export const loansTestData: Array<LoanInterface> = [
  {
    id: "1234",
    token: "DAI",
    collateralToken: "ETH",
    transactionHash: "0xxxxxxxxxxxxxxxxxxxxxxx",
    terms: {
      interestRate: 1,
      collateralRatio: 60,
      maxLoanAmount: 500,
      duration: 1,
      expiryAt: 1598195687893,
    },
    startDate: 1598995687893,
    endDate: 1598195687893,
    amountBorrowed: 500,
    status: StatusTypes["Active"],
    repayments: [{ amount: 1 }],
    totalRepaidAmount: 0,
    totalOwedAmount: 5,
    collateralDeposits: [{ amount: 0.71 }],
    totalCollateralDepositsAmount: 0.71,
    collateralWithdrawns: [{ amount: 1 }],
    totalCollateralWithdrawalsAmount: 0,
  },
  {
    id: "1244",
    token: "USDC",
    collateralToken: "LINK",
    transactionHash: "0xxxxxxxxxxxxxxxxxxxxxxx",
    terms: {
      interestRate: 1,
      collateralRatio: 70,
      maxLoanAmount: 150,
      duration: 1,
      expiryAt: 1598195687893,
    },
    startDate: 1598995687893,
    endDate: 1598195687893,
    amountBorrowed: 5000,
    status: StatusTypes["Active"],
    repayments: [{ amount: 1 }],
    totalRepaidAmount: 0,
    totalOwedAmount: 50,
    collateralDeposits: [{ amount: 40 }],
    totalCollateralDepositsAmount: 40,
    collateralWithdrawns: [{ amount: 1 }],
    totalCollateralWithdrawalsAmount: 0,
  },
  {
    id: "1254",
    token: "USDC",
    collateralToken: "LINK",
    transactionHash: "0xxxxxxxxxxxxxxxxxxxxxxx",
    terms: {
      interestRate: 1,
      collateralRatio: 60,
      maxLoanAmount: 50,
      duration: 1,
      expiryAt: 1598995687893,
    },
    startDate: 1598995687893,
    endDate: 1598995687893,
    amountBorrowed: 5000,
    status: StatusTypes["Active"],
    repayments: [{ amount: 1 }],
    totalRepaidAmount: 0,
    totalOwedAmount: 11,
    collateralDeposits: [{ amount: 4 }],
    totalCollateralDepositsAmount: 4,
    collateralWithdrawns: [],
    totalCollateralWithdrawalsAmount: 0,
  },
  {
    id: "1264",
    token: "DAI",
    collateralToken: "ETH",
    transactionHash: "0xxxxxxxxxxxxxxxxxxxxxxx",
    terms: {
      interestRate: 1,
      collateralRatio: 60,
      maxLoanAmount: 50,
      duration: 1,
      expiryAt: 1598995687893,
    },
    startDate: 1598995687893,
    endDate: 1598995687893,
    amountBorrowed: 500,
    status: StatusTypes["Closed"],
    repayments: [{ amount: 1 }],
    totalRepaidAmount: 0,
    totalOwedAmount: 20,
    collateralDeposits: [{ amount: 0.81 }],
    totalCollateralDepositsAmount: 0.81,
    collateralWithdrawns: [{ amount: 1 }],
    totalCollateralWithdrawalsAmount: 0,
  },
];
